### ISSUE TITLE
Do I need config files?

### ISSUE THREAD

**Issue by rohrsh** [Sysadminfromhell/corosyncdevice#1]
Hi there. I'm aiming to run this on docker on a Raspberry Pi (64 bit) node.

I put together this docker compose which I suppose pulls from Docker Hub. 

```
  qnetd:
    container_name: proxmox-qdevice
    image: safhdev/corosyncdevice:debianlatest    
    ports:
      - "22:22"
      - "5403:5403"
    environment:
      - "passwd=somerootpasswd"
    volumes:
     - /mnt/nfs_dockerfiles/qdevice-rack/run/sshd:/run/sshd 
     - /mnt/nfs_dockerfiles/qdevice-rack/etc/ssh:/etc/ssh
     - /mnt/nfs_dockerfiles/qdevice-rack/etc/corosync:/etc/corosync 
    restart: unless-stopped
    hostname: qdevice-rack
    networks: 
      vlan:
        ipv4_address: 172.22.1.5
```

It doesn't load. Logs show repeated version of this: 

2025-01-08 07:30:13,979 INFO spawned: 'corosync-qnetd' with pid 15
2025-01-08 07:30:13,990 INFO spawned: 'sshd' with pid 16
2025-01-08 07:30:14,023 WARN exited: corosync-qnetd (exit status 1; not expected)
2025-01-08 07:30:14,066 WARN exited: sshd (exit status 1; not expected)

Q: Do I need to create my own config files and place them in my docker bind mounts, or are they created on first run? e.g. /etc/corosync/corosync.conf, /etc/ssh/sshd_config and keys.
